spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to mybank , cards related prod api"
  contactDetails:
    name: "jayshri gaikwad"
    email: "jayshri@gmail.com"
  onCallSupport:
    - 5300404094
    - 4839994939
