spring:
  config:
    activate:
      on-profile : "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to mybank , account related prod api"
  contactDetails:
    name: "poonam gaikwad"
    email: "poonam@gmail.com"
  onCallSupport:
    - 5300404094
    - 4839994939
