spring:
  application:
    name: "configserver"


  profiles:
#    active: native
    active: git

  cloud:
    config:
      server:
        git:
#          fetches config files from git repo
          uri: "https://github.com/Piya308/config-repo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
          #if you config files is in same project then write below
#          search-locations: "classpath:/config"
        #if your config files are kept in file system
#          search-locations: "file:///H:/config"
encrypt:
  key: mK3P862OzNNaClcOzQFBT9Nb2OCGj36U

server:
  port: 8071


