build:
  version: "3.0"

accounts:
  message: "Welcome to mybank , accounts related local api"
  contactDetails:
    name: "poonam gaikwad"
    email: "poonam@gmail.com"
  onCallSupport:
    - 5300404094
    - 4839994939
