build:
  version: "1.0"

loans:
  message: "Welcome to mybank , loans related prod api"
  contactDetails:
    name: "poonam gaikwad"
    email: "poonam@gmail.com"
  onCallSupport:
    - 5300404094
    - 4839994939
